# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Xianming Liu
tagline:             Computer Vision, Machine Learning and Crowdsourcing
url:                 http://web.engr.illinois.edu/~xliu102/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Xianming Liu
  email:             liuxianming@gmail.com

# Custom vars
version:             1.0.0
github:

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
