title : Xianming Liu
tagline: Flying Over the Cuckoo's Nest
author :
  name : Xianming Liu
  email : xliu102@illinois.edu

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

markdown: pandoc
pandoc:
   extensions: [smart, mathjax]

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews
gitstamps: yes
repo: https://github.com/liuxianming/liuxianming.github.io # used in linking history

baseurl: '/'

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
